### ISSUE TITLE
Hiding a trace with AnalogSignalSourceWithScatter sometimes causes a crash

### ISSUE THREAD

**Issue by jpgill86** [NeuralEnsemble/ephyviewer#63]
If I run the `trace_viewer_with_marker.py` example and try to hide most or all of the channels with markers (0, 5, 8, 10), ephyviewer will crash.

In my neurotic app's example, hiding just one channel with markers is enough to crash it.

**Comment by jpgill86** [comment]
Here's the traceback:

```python
Traceback (most recent call last):
  File "d:\users\jeffrey\documents\python-dev\ephyviewer\git-repo\ephyviewer\ephyviewer\traceviewer.py", line 348, in on_request_data
    sigs_chunk, dict_scatter = self.get_data(t, t_start, t_stop, total_gains, total_offsets, visibles, decimation_method)
  File "d:\users\jeffrey\documents\python-dev\ephyviewer\git-repo\ephyviewer\ephyviewer\traceviewer.py", line 336, in get_data
    dict_scatter[k] = (np.concatenate(x), np.concatenate(y))
  File "C:\Users\Jeffrey\Miniconda3\envs\py3\lib\site-packages\pyqtgraph\numpy_fix.py", line 13, in concatenate
    return np.concatenate_orig(vals, *args, **kwds)
ValueError: need at least one array to concatenate
```
